# Generated by Django 3.1 on 2021-06-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122, null=True)),
                ('email', models.EmailField(max_length=122, null=True)),
                ('account_no', models.CharField(max_length=122, null=True)),
                ('ifsc_code', models.CharField(max_length=122, null=True)),
                ('amount', models.IntegerField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='transaction_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=122, null=True)),
                ('source_acc_no', models.CharField(max_length=122, null=True)),
                ('Current_balance', models.IntegerField(null=True)),
                ('money_deposit', models.IntegerField(null=True)),
                ('destination_name', models.CharField(max_length=122, null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
